language: php

php:
  - 8.0

sudo: false

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --no-suggest --prefer-dist

script:
    - vendor/bin/phpunit
